baseURL                = "https://davidliois.com/"
languageCode           = "en"
defaultContentLanguage = "en"
title                  = "David Liois Jayadi"
theme                  = "hugo-coder"
enableEmoji            = true

[pagination]
pagerSize = 6

[services]
[services.disqus]

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author      = "David Liois Jayadi"
description = "David Liois Jayadi's personal website"
keywords    = "blog,developer,personal"

info = [
    "Software Engineer",
]

avatarURL             = "images/profile.jpg"
dateFormat            = "02 January 2006"
since                 = 2023
rtl                   = false
colorScheme           = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems       = 5

customCSS = [
]
customSCSS = [
]
customJS = [
]
customRemoteJS = [
]

[taxonomies]
category = "categories"
series   = "series"
tag      = "tags"
author   = "authors"

[[params.social]]
name   = "Github"
icon   = "fa-brands fa-github fa-2x"
weight = 1
url    = "https://github.com/dapod93/"
target = "_blank"

[[params.social]]
name   = "LinkedIn"
icon   = "fa-brands fa-linkedin fa-2x"
weight = 2
url    = "https://www.linkedin.com/in/david-liois-jayadi-76735573/"
target = "_blank"

[[params.social]]
name   = "Instagram"
icon   = "fa-brands fa-instagram fa-2x"
weight = 3
url    = "https://www.instagram.com/davidliois93/"
target = "_blank"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name   = "About"
weight = 1
url    = "about/"

[[languages.en.menu.main]]
name   = "About"
weight = 1
url    = "about/"
[[languages.en.menu.main]]
name   = "Blog"
weight = 2
url    = "posts/"

[[languages.en.menu.main]]
name   = "Projects"
weight = 3
url    = "projects/"

[languages.id]
languageName = ":indonesia:"
title        = "David Liois Jayadi"

[languages.id.params]
author      = "David Liois Jayadi"
description = "Situs pribadi David Liois Jayadi"
info        = "Software Engineer"
keywords    = "blog,developer,personal,pengembang,pribadi"

[[languages.id.menu.main]]
name   = "Tentang"
weight = 1
url    = "about/"

[[languages.id.menu.main]]
name   = "Blog"
weight = 2
url    = "posts/"

[[languages.id.menu.main]]
name   = "Proyek"
weight = 3
url    = "projects/"
